export default [
    {
        id: 1,
        location: 'Netherlands',
        title: 'Bloemendaal aan Zee',
        googleMapsUrl:'https://goo.gl/maps/duESR6ZSrkxrbH2Y9',
        moyy: 'August 2021',
        description: 'Bloemendaal aan Zee is a seaside resort and neighbourhood in the municipality Bloemendaal, in North Holland province, the Netherlands. It is between the beaches of IJmuiden to the north and Zandvoort to the south and surrounded by the dunes of the Zuid-Kennemerland National Park.',
        beer: "Brouwerij 't IJ IJwit",
        beerUrl: 'https://www.brouwerijhetij.nl/home_en/?lang=en',
        imageUrl: 'sea.png',
    },
    {
        id: 2,
        location: 'Germany',
        title: 'Schönau am Königssee',
        googleMapsUrl:'https://goo.gl/maps/hJG5Rx7JA4gugJJN7',
        moyy: 'August 2021',
        description: 'Schönau am Königssee is a municipality in the district of Berchtesgadener Land in the German state of Bavaria. It is located at the northern end of the Königssee lake.',
        beer: 'Franziskaner Hefe-Weissbier',
        beerUrl: 'https://franziskaner-weissbier.de/',
        imageUrl: 'alps.png',
    },
    {
        id: 3,
        location: 'Austria',
        title: 'St. Wolfgang im Salzkammergut',
        googleMapsUrl:'https://goo.gl/maps/3CjsHZqczu6QTLjr8',
        moyy: 'August 2021',
        description: 'St. Wolfgang im Salzkammergut is an Austrian town east of Salzburg, in the The Pilgrimage Church, overlooking Lake Wolfgangsee, houses a towering, intricately carved winged altarpiece. Ferries, including an 1873 paddle steamer, cruise the lake, which is ringed by mountains.',
        beer: 'Weihenstephaner Heffe Weissbier',
        beerUrl: 'https://www.weihenstephaner.de/en/',
        imageUrl: 'lake.png',
    }
]